# Generated by Django 2.2 on 2019-04-29 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2019, 4, 29, 22, 43, 6, 878650))),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
