# Generated by Django 2.2 on 2019-05-01 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190501_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 20, 56, 28, 538774)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 20, 56, 28, 538808)),
        ),
    ]
