# Generated by Django 2.2 on 2019-05-01 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190501_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 21, 5, 10, 768821)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 21, 5, 10, 768857)),
        ),
    ]
